### ISSUE TITLE
Support non-array parameters

### ISSUE THREAD

**Issue by macalinao** [fgnass/typed-rpc#13]
The JSON-RPC spec allows for passing in named parameters rather than an array of parameters. Can you add support for this?

**Comment by fgnass** [comment]
The core idea of `typed-rpc` is that both client and server are implemented in TypeScript and share their types. Since TypeScript does not support named parameters, I'm unsure what exactly you have in mind.

The only way I can think of that comes close to named parameters would be something like this (which is already supported):

```ts
type HelloParams = {
  greeting: string;
  name: string;
};

export const myService = {
  hello({greeting, name}: HelloParams) {
    return `${greeting} ${name}!`;
  },
};
```

**Comment by macalinao** [comment]
That's fair-- I'm calling my service from Python and the library I'm using there doesn't create an array

My solution looks something like this, if anyone else encounters this issue:

```
  const { params, ...reqWithoutParams } = req;
  // for some reason this library enforces an array type, but we will always pass named parameters
  const newReq = { ...reqWithoutParams, params: [params] };
  if (!isJsonRpcRequest(newReq)) {
    throw new APIError("not a json rpc request");
  }
  try {
    return await handleRpc(
      newReq,
      // @ts-ignore
      service
    );
  } catch (e) {
    throw new APIError("Could not handle RPC", e);
  }
  ```

**Comment by fgnass** [comment]
That's an interesting use-case. Thanks for sharing your solution!
